# Generated by Django 3.1.2 on 2020-11-02 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20201101_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('chat_slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 1, 17, 54, 16, 288150)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 1, 17, 54, 16, 288150)),
        ),
    ]
