# Generated by Django 3.1.2 on 2020-11-04 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20201103_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchats',
            name='with_user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 17, 9, 58, 203168)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 17, 9, 58, 203168)),
        ),
    ]
